"""
Django settings for djangoapi project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os, sys
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
DJANGO_SUPERUSER_USERNAME=(os.getenv('DJANGO_SUPERUSER_USERNAME'))
BASE_DIR = Path(__file__).resolve().parent.parent
EPSG_FOR_GEOMETRIES=int(os.getenv('EPSG_FOR_GEOMETRIES',4326))
ST_SNAP_PRECISION=float(os.getenv('ST_SNAP_PRECISION',0.0001))
MAX_NUMBER_OF_RETRIEVED_ROWS=int(os.getenv('MAX_NUMBER_OF_RETRIEVED_ROWS',1000))
DJANGO_KNOX_AUTOMATICALLY_REMOVE_TOKENS=os.getenv("DJANGO_KNOX_AUTOMATICALLY_REMOVE_TOKENS", "True").lower() in ('true', '1', 't')

DJANGO_SUPERUSER_EMAIL=os.getenv('DJANGO_SUPERUSER_EMAIL')
FORCE_SCRIPT_NAME=os.getenv('FORCE_SCRIPT_NAME')

API_URL=os.getenv('API_URL')#El dominio y alias de acceso a la API, con BARRA FINAL. 
                            #Ej https://mydomain.com/metatierrascol-api/
WEB_URL=os.getenv('WEB_URL')#La dirección a la web. Se usa en los emails
TEMPLATE_ASSETS_URL=os.getenv('TEMPLATE_ASSETS_URL')#dirección de los archivos
                                    #estáticos usados en las plantillas

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY','DKLSJGHFHF654165464kasdjhadkgf')

# SECURITY WARNING: don't run with debug turned on in production!
REMOTE_DEBUG = False
DEBUG = os.getenv("DEBUG", 'False').lower() in ('true', '1', 't')

allowed_hosts_str = os.getenv('DJANGO_ALLOWED_HOSTS')
if allowed_hosts_str:
    # Si la variable de entorno es el comodín, asigna la lista con el comodín
    if allowed_hosts_str == '*':
        ALLOWED_HOSTS = ['*']
    else:
        # Si son hosts específicos, los separa y limpia
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]
else:
    # Si la variable no existe, asigna una lista vacía para seguridad
    ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    #required by geodjango
    'django.contrib.gis',
    #para el CORS
    'corsheaders',
    'rest_framework',
    'rest_framework_gis',
    #https://jazzband.github.io/django-rest-knox/
    'knox',
    'django_filters',
    #'drf_yasg',
    #add all your django apps here
    'drf_spectacular',
    #'guardian',    
    'core',
    'codelist',
    'buildings',
    'flowers',
    'accidentes',
    'smartcity_app'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
#    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#para el CORS. Solo el navegador. Las APPs no tienen CORS
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ORIGINS = [WEB_URL]

#necressary to allow the cookies to be sent in the header of the request
CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'djangoapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['core'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoapi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#Sirve para crear la base de datos de test para ejecutar los test
#con el módulo create_db_test.py
#python create_db_test.py
MODE_TEST = os.getenv("MODE_TEST", 'False').lower() in ('true', '1', 't')
if MODE_TEST:
    DATABASE_NAME = 'test_'+ os.getenv('POSTGRES_DB')
    print(f'Base de datos en modo test: {DATABASE_NAME}')
else:
    DATABASE_NAME = os.getenv('POSTGRES_DB')

DATABASES = {
    'default': {
        #ENGINE': 'django.db.backends.postgresql_psycopg2',
        #required by geodjango
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': DATABASE_NAME,
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
        'OPTIONS': {
            'options': '-c search_path=public',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#On logout, redirect to the login page
#LOGOUT_REDIRECT_URL = "/accounts/login/"

#if you try to use a view without being logged in, redirect to the following URL
if DEBUG:
    LOGIN_URL = "/core/not_loggedin/"
else:
    LOGIN_URL = "/desweb-api/core/not_loggedin/"

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': ('knox.auth.TokenAuthentication',),
    'EXCEPTION_HANDLER': 'core.myLib.drf.custom_exception_handler',
}

REST_KNOX = {
    #'USER_SERIALIZER':'accounts.serializers.UserSerializer',
    'TOKEN_TTL': timedelta(days=int(os.getenv("DJANGO_SESSION_EXPIRY_DAYS", 1))),
    'TOKEN_LIMIT_PER_USER':int(os.getenv("TOKEN_LIMIT_PER_USER")),
}

#Email
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS','True').lower() == 'true' #Devuelve True si se cumple
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_UPV = os.getenv('EMAIL_UPV')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_FROM = os.getenv('EMAIL_FROM')
ADMINS=[(os.getenv('DJANGO_EMAIL_FOR_ERRORS_USER_NAME'), os.getenv('DJANGO_EMAIL_FOR_ERRORS_EMAIL'))]


#Para realizar los tests automáticos
#Comando:
#   python manage.py test --keepdb
#
#--keepdb: Le dice a Django: "No intentes borrar la base de datos al terminar".
TESTING = 'test' in sys.argv

if TESTING:
     DATABASES['default']['NAME'] = 'test_'+ os.getenv('POSTGRES_DB')
     # Esto es la clave: evita que Django intente crear la BD
     DATABASES['default']['TEST'] = {
         'NAME': 'test_'+ os.getenv('POSTGRES_DB'),
         'CREATE_DB': False, #no intenta crear la bbdd al empezar
     }