# Generated by Django 6.0.1 on 2026-03-05 17:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrilesBici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('longitud_metros', models.FloatField(blank=True, null=True)),
                ('tipo_pavimento', models.CharField(blank=True, max_length=50, null=True)),
                ('sentido_unico', models.BooleanField(blank=True, default=False, null=True)),
                ('anyo_construccion', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=25830)),
            ],
        ),
        migrations.CreateModel(
            name='Contenedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residuo', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad_litros', models.FloatField(blank=True, null=True)),
                ('fecha_ultima_recogida', models.DateField(blank=True, null=True)),
                ('estado_conservacion', models.CharField(blank=True, max_length=50, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=25830)),
            ],
        ),
        migrations.CreateModel(
            name='Parques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('area_hectareas', models.FloatField(blank=True, null=True)),
                ('tiene_zona_infantil', models.BooleanField(blank=True, default=False, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
                ('tipo_mantenimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=25830)),
            ],
        ),
    ]
