# Generated by Django 6.0.1 on 2026-03-25 17:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrilesbici',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=25830),
        ),
        migrations.AlterField(
            model_name='contenedores',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=25830),
        ),
        migrations.AlterField(
            model_name='parques',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=25830),
        ),
    ]
